// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlF86otG1fpZSCn9kcAcWUu5DBQsnVGR4',
    appId: '1:133991597476:web:d7c885a512a305d7566d31',
    messagingSenderId: '133991597476',
    projectId: 'mara-attendance-system',
    authDomain: 'mara-attendance-system.firebaseapp.com',
    storageBucket: 'mara-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATnb009H8113YMtxgDHgPZyChj7y6yWmk',
    appId: '1:133991597476:android:3019e2b720c1ff1c566d31',
    messagingSenderId: '133991597476',
    projectId: 'mara-attendance-system',
    storageBucket: 'mara-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4A7Y8u7y0k4xrlUM-E_AhWb5HgVcxXDc',
    appId: '1:133991597476:ios:da79f82f60d27598566d31',
    messagingSenderId: '133991597476',
    projectId: 'mara-attendance-system',
    storageBucket: 'mara-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4A7Y8u7y0k4xrlUM-E_AhWb5HgVcxXDc',
    appId: '1:133991597476:ios:da79f82f60d27598566d31',
    messagingSenderId: '133991597476',
    projectId: 'mara-attendance-system',
    storageBucket: 'mara-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlF86otG1fpZSCn9kcAcWUu5DBQsnVGR4',
    appId: '1:133991597476:web:9d3f743b5b5d779a566d31',
    messagingSenderId: '133991597476',
    projectId: 'mara-attendance-system',
    authDomain: 'mara-attendance-system.firebaseapp.com',
    storageBucket: 'mara-attendance-system.firebasestorage.app',
  );
}
